from django.urls import re_path

from . import views

urlpatterns = [
    re_path(r"^student/$", views.StudentListAPI.as_view(), name='student_list_api'),
    re_path(r"^student/(?P<pk>[0-9])/$", views.StudentAPI.as_view(), name='student_api'),
    re_path(r"^user/$", views.UserListAPI.as_view(), name='user_list_api'),
    re_path(r"^user/(?P<pk>[0-9])/$", views.UserAPI.as_view(), name='user_api'),
    re_path(r"^dojo/(?P<pk>[0-9])/$", views.DojoAPI.as_view(), name='dojo_api'),
    re_path(r"^dojo/$", views.DojoListAPI.as_view(), name='dojo_list_api'),
    re_path(r"^class/$", views.ClassListAPI.as_view(), name='class_list_api'),
    re_path(r"^class/(?P<pk>[0-9])/$", views.ClassAPI.as_view(), name='class_api'),
    re_path(r"^class_view/$", views.ClassTemplateView.as_view(), name='class_views'),
    re_path(r"^dojo_view/$", views.DojoTemplateView.as_view(), name='dojo_views'),
    re_path(r"^user_view/$", views.UserTemplateView.as_view(), name='user_views'),
    re_path(r"^knockout_view/$", views.KnockoutTemplateView.as_view(), name='knockout_views'),
    re_path(r"^participants_view/$", views.ParticipantsTemplateView.as_view(), name='participants_views'),
    re_path(r"^tournament_view/$", views.TournamentTemplateView.as_view(), name='tournament_views'),
    re_path(r"^user_profile_view/$", views.UserProfileTemplateView.as_view(), name='user_profile_views'),
    re_path(r"^profile/$", views.ProfileListAPI.as_view(), name='profile_list_api'),
    re_path(r"^profile/(?P<pk>[0-9])/$", views.ProfileAPI.as_view(), name='profile_api'),
    re_path(r"^category/$", views.CategoryListAPI.as_view(), name='category_list_api'),
    re_path(r"^category/(?P<pk>[0-9])/$", views.CategoryAPI.as_view(), name='category_api'),
    re_path(r"^userprofile/$", views.UserProfileListAPI.as_view(), name='userprofile_list_api'),
    re_path(r"^userprofile/(?P<pk>[0-9])/$", views.UserProfileAPI.as_view(), name='userprofile_api'),
    re_path(r"^tournamentprofile/$", views.TournamentProfileListAPI.as_view(), name='tournament_profile_list_api'),
    re_path(r"^tournamentprofile/(?P<pk>[0-9])/$", views.TournamentProfileAPI.as_view(), name='tournament_profile_api'),
    re_path(r"^teacher/$", views.TeacherListAPI.as_view(), name='teacher_list_api'),
    re_path(r"^teacher/(?P<pk>[0-9])/$", views.UserAPI.as_view(), name='teacher_api'),
    re_path(r"^tournament/$", views.TournamentListAPI.as_view(), name='tournament_list_api'),
    re_path(r"^tournament/(?P<pk>[0-9])/$", views.TournamentAPI.as_view(), name='tournament_api'),
    re_path(r"^participants/$", views.ParticipantsListAPI.as_view(), name='participants_list_api'),
    re_path(r"^participants/(?P<pk>[0-9])/$", views.ParticipantsAPI.as_view(), name='participants_api'),
    re_path(r"^competitor/$", views.CompetitorListAPI.as_view(), name='competitor_list_api'),
    re_path(r"^competitor/(?P<pk>[0-9])/$", views.CompetitorAPI.as_view(), name='competitor_api'),
    re_path(r"^referee/$", views.RefereeListAPI.as_view(), name='referee_list_api'),
    re_path(r"^referee/(?P<pk>[0-9])/$", views.RefereeAPI.as_view(), name='referee_api'),
    re_path(r"^knockout/$", views.KnockoutListAPI.as_view(), name='knockout_list_api'),
    re_path(r"^knockout/(?P<pk>[0-9])/$", views.KnockoutAPI.as_view(), name='knockout_api'),
    re_path(r"^token/$", views.get_csrf_token, name='csrf_token'),
]