# Generated by Django 2.2.4 on 2019-10-08 02:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(db_column='news_name', max_length=200)),
                ('text', models.TextField(db_column='news_content')),
                ('published', models.DateTimeField(db_column='published_date', default=django.utils.timezone.now)),
                ('edited', models.DateTimeField(blank=True, db_column='Last_edited', null=True)),
            ],
        ),
    ]
