# Generated by Django 2.2.4 on 2019-10-04 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='category_name', max_length=100)),
                ('order', models.PositiveIntegerField(db_column='category_order', unique=True)),
                ('color', models.CharField(db_column='category_color', max_length=6)),
                ('description', models.CharField(db_column='category_description', max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Dojo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='dojo_name', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='profile_name', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='user_name', max_length=100)),
                ('cbj_id', models.CharField(db_column='cbj_id', max_length=100)),
                ('primary_phone', models.CharField(db_column='primary_phone', max_length=100)),
                ('alternative_phone', models.CharField(db_column='alternative_phone', max_length=100)),
                ('email', models.EmailField(db_column='email', max_length=254, unique=True)),
                ('cpf', models.IntegerField(db_column='cpf_number', editable=False, max_length=11)),
                ('notes', models.CharField(db_column='notes', max_length=1000)),
                ('rg', models.IntegerField(editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.Category')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.Profile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.User')),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dojo', models.ForeignKey(db_column='dojo_id', on_delete=django.db.models.deletion.CASCADE, related_name='register_class_dojo', related_query_name='register_classs', to='register.Dojo')),
                ('student', models.ForeignKey(db_column='student_id', on_delete=django.db.models.deletion.CASCADE, related_name='register_class_student', related_query_name='register_classs_student', to='register.UserProfile')),
                ('teacher', models.ForeignKey(db_column='teacher_id', on_delete=django.db.models.deletion.CASCADE, related_name='register_class_teacher', related_query_name='register_classs_teacher', to='register.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('register.userprofile',),
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('register.userprofile',),
        ),
    ]
