# Generated by Django 2.2.4 on 2019-10-04 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cpf',
            field=models.IntegerField(db_column='cpf_number', max_length=11),
        ),
        migrations.AlterField(
            model_name='user',
            name='notes',
            field=models.CharField(db_column='notes', max_length=1000, null=True),
        ),
    ]
