# Generated by Django 2.2.4 on 2019-10-04 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_auto_20191004_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='rg',
            field=models.IntegerField(),
        ),
    ]
