# Generated by Django 2.2.4 on 2019-11-17 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_auto_20191117_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_associate_card_expired',
            field=models.BooleanField(default=True),
        ),
    ]
