# Generated by Django 2.2.4 on 2019-11-17 23:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_user_is_associate_card_expired'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='student',
            field=models.ForeignKey(db_column='student_id', on_delete=django.db.models.deletion.CASCADE, related_name='register_class_student', related_query_name='register_classs_student', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='class',
            name='teacher',
            field=models.ForeignKey(db_column='teacher_id', on_delete=django.db.models.deletion.CASCADE, related_name='register_class_teacher', related_query_name='register_classs_teacher', to=settings.AUTH_USER_MODEL),
        ),
    ]
