# Generated by Django 2.2.4 on 2019-11-17 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0005_auto_20191117_2301'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
