# Generated by Django 2.2.4 on 2019-11-18 00:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0006_tournament_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knockout',
            name='competitor_one',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='register_knockout_competitor_one', related_query_name='register_knockouts_competitor_one', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='knockout',
            name='competitor_two',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='register_knockout_competitor_two', related_query_name='register_knockouts_competitor_two', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='knockout',
            name='referee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='register_knockouts_referee', related_query_name='register_knockouts_referee', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='knockout',
            name='winner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='register_knockouts_winner', related_query_name='register_knockouts_winner', to=settings.AUTH_USER_MODEL),
        ),
    ]
